
server:
  port: 8085

spring:
  application:
    name: nacos-sentinel-demo
  cloud:
    nacos:
      discovery:
        #该项目主要是测试sentinel,nacos不是必需的
        server-addr: 47.96.111.179:8848  #nacos 2.x后需要开放出9848和9849两个新端口，不然客户端无法连接服务器，我已经在阿里云服务器开放过了
    sentinel:
      eager: true
      transport:
        dashboard: 47.96.111.179:8888  #sentinel dashboard 的服务器地址和端口